
name: "deploy backend application"

on:
  push:
    - main
    - dev
    - staging

jobs:

  build-push:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: echo "run docker build command"

      - name: push docker image
        run: echo "run docker push command"


  deploy:
    name: deploy to Azure container instance
    runs-on: ubuntu-latest
    steps:
      - name: deploy the image
        shell: bash
        run: |
          if [[ $GITHUB_REF == "main" ]] 
          then
            echo "run command to deploy to production"
          elif [[ $GITHUB_REF == "dev" ]]
          then
            echo "run command to deploy to dev"
          elif [[ $GITHUB_REF == "staging" ]]
          then
            echo "run command to deploy to staging"
          fi
